# MPC configuration parameters
Model:
  C_matrix:
    - [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
    # - [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
    # - [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
    # - [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
    # - [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
    # - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
    # - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
  D_matrix:
    - [0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 0, 0, 0]
    # - [0, 0, 0, 0, 0, 0, 0, 0]
    # - [0, 0, 0, 0, 0, 0, 0, 0]
    # - [0, 0, 0, 0, 0, 0, 0, 0]
    # - [0, 0, 0, 0, 0, 0, 0, 0]
    # - [0, 0, 0, 0, 0, 0, 0, 0]
    # - [0, 0, 0, 0, 0, 0, 0, 0]

cost_function:
  Q_diag: #ref state deviation weight matrix
    - 10
    - 10
    - 10
    - 1
    - 1
    - 1
    # - 10
    # - 10
    # - 10
    # - 10
    # - 10
    # - 10
  R_diag: #ref input deviation weight matrix
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1

constraints: #different input constraints from reports etc. double check
  u_lim:
    max_forces_and_torques:
      - 85
      - 85
      - 120
      - 26
      - 14
      - 22
    thruster_forces:
      - 31
      - 31
      - 31
      - 31
      - 31
      - 31
      - 31
      - 31
    range_1_1:
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1

  x_lim: #limit on states
    - inf
    - inf
    - inf
    - inf
    - inf
    - inf
    - inf
    - inf
    - inf
    - inf
    - inf
    - inf

horizon: #MPC control horizon
  N: 30

slack: #slack penalty
  kappa: 100

terminal_set: #0 terminal set, do not change
  Cx:
    - 1e-6
    - 1e-6
  Cb:
    - 1e-6

T_matrices:
  config1:
    - [0.7071, 0.7071, -0.7071, -0.7071, 0, 0, 0, 0]
    - [-0.7071, 0.7071, -0.7071, 0.7071, 0, 0, 0, 0]
    - [0, 0, 0, 0, -1, 1, 1, -1]
    - [0.06, -0.06, 0.06, -0.06, -0.218, -0.218, 0.218, 0.218]
    - [0.06, 0.06, -0.06, -0.06, 0.12, -0.12, 0.12, -0.12]
    - [-0.1888, 0.1888, 0.1888, -0.1888, 0, 0, 0, 0]

  config2:
    - [0.7071, 0.7071, -0.7071, -0.7071, 0, 0, 0, 0]
    - [-0.7071, 0.7071, -0.7071, 0.7071, 0, 0, 0, 0]
    - [0, 0, 0, 0, -1, 1, 1, -1]
    - [0, 0, 0, 0, 0.218, 0.218, -0.218, -0.218]
    - [0, 0, 0, 0, 0.12, -0.12, 0.12, -0.12]
    - [-0.1888, 0.1888, 0.1888, -0.1888, 0, 0, 0, 0]

  config3:
    - [-0.71, -0.71, 0.71, 0.71, 0, 0, 0, 0]
    - [0.71, -0.71, 0.71, -0.71, 0, 0, 0, 0]
    - [0, 0, 0, 0, 1.0, 1.0, 1.0, 1.0]
    - [-0.06, 0.06, -0.06, 0.06, 0.22, -0.22, 0.22, -0.22]
    - [-0.06, -0.06, 0.06, 0.06, -0.12, -0.12, 0.12, 0.12]
    - [0.99, -0.99, -0.99, 0.99, 0, 0, 0, 0]

selected_T_matrix: config2  # Change this to config2 or config3 as needed
